spring:
  datasource:
    url: jdbc:mysql://localhost:3307/vollmed_api
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
